M48
; DRILL file {KiCad (6.0.10-0)} date Saturday, January 28, 2023 at 09:33:10 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-28T21:33:10-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X113.97Y-97.46
X115.24Y-49.2
X166.04Y-64.44
X166.04Y-92.38
T0
M30
